definitions:
  models.Person:
    properties:
      address:
        type: string
      name:
        type: string
      number:
        type: string
    type: object
info:
  contact: {}
paths:
  /persons:
    post:
      consumes:
      - application/json
      description: add person by information
      operationId: add-person
      parameters:
      - description: query params
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            string:
              type: string
          schema:
            type: string
      summary: add person
      tags:
      - persons
  /persons/{name}:
    get:
      consumes:
      - application/json
      description: get string by Name
      parameters:
      - description: Person Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
      summary: get a person
      tags:
      - persons
swagger: "2.0"
